### PR TITLE
converted offline download example to class

### PR DESCRIPTION
**Pull request by Cintrust**
this is to enable easy maintainace

### CODE REVIEW

**Comment by Cintrust** [comment]
also fixed issue #21 and issue #20

**Comment by cubiclesoft** [comment]
Rejecting this pull request for multiple reasons:

* Offline downloading is not the main purpose of this library.  The original example is a functional, standalone example I threw together in a weekend that is not part of the core library.  You are certainly free to turn it into a class but don't push unnecessary files into the upstream project.  When in doubt, contact the project owner separately before opening a pull request.
* Bad constructor design.  Constructors should only ever be simple initializers.
* Breaks local system security.  Never `chmod 777`.
* Contains a TODO.  Always finish what you start.
* Unlicensed code.
* Doesn't properly load CubicleSoft classes.
* Doesn't follow CubicleSoft coding style.

**Comment by Cintrust** [comment]
So should I go ahead and turn it into a class with the corrections you made, before pushing again?.
Or your totally against that idea?. I got that part mixed up.

Additionally direction to where I can get the authors contact would be nice, for easy communication

**Comment by cubiclesoft** [comment]
I meant you are free to do whatever you want with the code under the MIT/LGPL license.  I can't think of a use-case where having the code in a class makes any sense.  Classes generally introduce additional complexity, which makes them less maintainable, not more.  With your approach, you now have to have multiple files open to debug the application instead of just one file.  I'd need to see a demonstrable use-case that shows why this part of the project needs to expand beyond what it already has.  Security vulnerabilities do not inspire confidence from this end, so that's a notable point against any argument you might make.  I recommend digesting the OWASP Top 10 before revisiting.

I was speaking in general when I said to contact a project owner before opening a pull request if you aren't sure that they will accept a specific addition to the project.  Communication is the most important part of developing software.  Doing so saves you the trouble of forking and opening a pull request that won't be accepted.

**Pull request closed without merging**
